import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Layout/Header";
import { ProductProvider } from "@/components/Layout/ProductContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MyStore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProductProvider>
          {children}
        </ProductProvider>
      </body>
    </html>
  );
}
